
extrace:extrace.cpp
	g++ -g ./extrace.cpp ./libvideocompare.a  -Wl,-rpath=/home/ubuntu/opencv-2.4.13/lib -L/home/ubuntu/opencv-2.4.13/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -L/usr/lib/x86_64-linux-gun/ -lgdk-x11-2.0 -o ./extrace
